version: "3.9"
services:
  python3:
    restart: always
    build: .
    container_name: "bocs"
    deploy:
      resources:
        limits:
          cpus: "64"
          memory: 60g
    memswap_limit: 64g
    working_dir: "/root/bocs"
    tty: true
    volumes:
      - .:/root/bocs/
